# Capitolo 2
## Statistiche descrittive
### Operazioni preliminari

```{r}
# carico le librerie necessarie
options(warn=-1)
library("survival")
library("survminer")
library("pander")
```

```{r}
# carico il dataset
dataset <-
  read.table(
    "../dataset.csv",
    na.strings = ".",
    sep = "\t",
    header = T,
    row.names = NULL
  )
```

```{r}
# Rimuovo l'id della riga
dataset <- dataset[,-1]

# Prendo solo le covariate cliniche
dataset <- dataset[1:7]

# Converto le variabili categoriche in categorie numeriche
dataset$Diam <- ifelse(dataset$Diam == "<=2cm", 0, 1)
dataset$N <- ifelse(dataset$N == "<4", 0, 1)
dataset$ER <- ifelse(dataset$ER == "Negative", 0, 1)
dataset$Grade <- ifelse(dataset$Grade == "Poorly diff",
                        0,
                        ifelse(dataset$Grade == "Intermediate", 1, 2))
```

### **Computazione statistiche**

```{r}
pander(summary(dataset), big.mark = ",") #-- statistiche 
```

```{r}
plot(dataset, pch = 19, cex = .5) #-- scatter plot multivariato
```

```{r}
par(mfrow = c(2, 4))
for (i in names(dataset))
{
  boxplot(dataset[, i],
          main = i,
          col = "lightblue",
          ylab = i)
}
```